### PR TITLE
Partial implementation of basic launch

### PR DESCRIPTION
**Pull request by dinoboff**
## Missing (next PRs):

- unit test (will need refactoring of firebase initialisation).
- returning outcome.
- return link to the UI.
- doesn't let instructor configure the launch (some dummy setting would be useful).
- launch data update (might not be relevant yet anyway).
- firebase auth token expiration (does firebase keep the user logged in once the original auth token expire?).

### Setup:

1. Instructor/admin request oauth1 keys from "https://{project-id}.firebaseapp.com/" or  "https://{project-id}.firebaseapp.com/lti/" .
1. HTTP triggered cloud function generate keys and render them.
1. Instructor configure his Tool Consumer (TC) to save the keys and setup an activity for this demo Tool Provider (TP).

### Launch

1. User send launch request to TP.
1. HTTP triggered cloud function authenticate oauth1 request using ims-lti
1. The functions saves the launch data (if the activity is new and the user has instructor role).
1. The functions create a firebase auth token.
1. The functions render a html page including the token, the launch resource link id and the TC consumer key (the domain for the resource, not the consumer secret).
1. HTML page use firebase auth token to log in user (instructor in the case).
1. HTML page display form to complete the activity.
1. User click button.
1. HTML page save the solution to the database.
1. A firebase event triggered cloud function verify the solution and save the grade (this part could have been ignored, the user could set her own grade, backend solution verification will be a typical use case).

## Issues:

- the UI is very basic.
- the presentation data are saved with the launch details; they don't need to be saved in the database and should only be sent with UI.

### CODE REVIEW

**Comment by dinoboff** [comment]
@scboesch Have you tried setting it up?

**Comment by scboesch** [comment]
@dinoboff is everything implemented sufficiently for me to try integrating with Moodle Cloud?

**Comment by dinoboff** [comment]
@scboesch You can generate the oauth1 keys, install the it on Moodle Cloud, create an activity in a course and launch it.

e.g https://fir-lti.firebaseapp.com/

Does the README describes development and deployment well enough? Can you clone the repo, create firebase project, a service account json file and try to run it locally or deploy a demo?

**Comment by scboesch** [comment]
I can clone the repo, create a new firebase project, and deploy following the ReadMe directions. I can also add the new LTI provider as an external tool in Moodle Cloud (LTI consumer) and create an activity. 

I can also install your deployment (fir-lti) as an LTI provider for my Moodle Cloud instance. The GUI appears properly when I display it after creating a new activity. 

When I try to complete either activity as an enrolled student, I do not see the button. Instead, I see an internal server error message. 
image

**Pull request merged**
